name:                slackworkcount
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/slackworkcount#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

default-extensions:
  - OverloadedStrings
dependencies:
  - base >= 4.7 && < 5
  - slack-web
  - bytestring
  - aeson
  - aeson-pretty
  - aeson-casing
  - string-conversions
  - time
  - time-locale-compat
  - text
  - mtl
  - Hclip
  - template-haskell
  - aeson-better-errors
  - deriveJsonNoPrefix

executables:
  slackworkcount:
    source-dirs: app
    main: Main.hs
    dependencies:
      - slackworkcount

library:
  source-dirs: src

tests:
  spec:
    source-dirs:
      - test
    main: Spec.hs
    dependencies:
      - slackworkcount
      - hspec
      - QuickCheck

