name:                automerge
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/automerge#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - github
  - optparse-generic
  - text
  - bytestring
  - slack-api
  - typed-process
  - string-conversions
  - path
  - bytestring
  - optparse-applicative
  - interpolate
  - extra

executables:
  swc:
    source-dirs: src
    main: SlackWorkCountMain.hs
